name: preprod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Task
      uses: pnorton5432/setup-task@v1
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Create private key file
      run: |
        mkdir -p creds
        echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > creds/streamlit.pem
        chmod 600 creds/streamlit.pem
    - name: Sync
      run: |
        task sync
    - name: Deploy to snowflake
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_AUTHENTICATOR: ${{ secrets.SNOWFLAKE_AUTHENTICATOR }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      run: |
        task deploy